# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='Education', help_text='The degree the student is pursuing', max_length=60),
            preserve_default=False,
        ),
    ]
