# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.CharField(help_text='A short summary about ASE. Maximum 400 characters.', max_length=400)),
                ('description_text', tinymce.models.HTMLField(help_text='Description about ASE', verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Last Name', max_length=30)),
                ('about_short', models.CharField(help_text='A short description about this member. Maximum 200 characters', max_length=200)),
                ('about_long', tinymce.models.HTMLField(help_text='A long description about this member.')),
                ('age', models.IntegerField(help_text='Age')),
                ('country', models.CharField(help_text='Country of origin', max_length=100)),
                ('profile_image', models.ImageField(upload_to='static/images/student/profiles')),
                ('funding_goal', models.FloatField(help_text='Total amount needed')),
                ('current_funding', models.FloatField(help_text='Current money raised')),
                ('graduation_date', models.DateField(help_text='Year of graduation')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Last Name', max_length=30)),
                ('position', models.CharField(help_text='What is his/her position at the company?', max_length=48)),
                ('about', models.CharField(help_text='A short description about this member. Maximum 200 characters', max_length=200)),
                ('profile_image', models.ImageField(upload_to='static/images/teamprofiles')),
            ],
        ),
    ]
