# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title. Maximum 100 characters', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='an unique identifier', max_length=100, unique=True)),
                ('body', tinymce.models.HTMLField(help_text='Blog body')),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(help_text='Author(s)', on_delete=django.db.models.deletion.CASCADE, to='home.TeamMember')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(help_text='Create a category for the blog', on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
    ]
