# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180422_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
