# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='tag_line',
            field=models.CharField(default='Sponsor a Student. Change a Life.', help_text='Home page tag line. Maximum 150 characters.', max_length=150),
            preserve_default=False,
        ),
    ]
