# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20180422_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title. Maximum 100 characters', max_length=100, unique=True)),
                ('body', tinymce.models.HTMLField(help_text='Blog body')),
                ('pub_date', models.DateField(auto_now_add=True, db_index=True)),
                ('thumbnail', models.ImageField(help_text='thumnail image', upload_to='static/images/student/blogs')),
                ('intext_image', models.ImageField(help_text='An in-text image', upload_to='static/images/student/blogs')),
                ('author', models.ForeignKey(help_text='Author(s)', on_delete=django.db.models.deletion.CASCADE, to='home.TeamMember')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(help_text='Create a category for the blog', on_delete=django.db.models.deletion.CASCADE, to='news_feeds.Category'),
        ),
    ]
